# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next
    pull: true

workspace:
  base: /test
  path: atomium

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION=5.6}
    environment:
    - DOCUMENT_ROOT=/test/atomium
    pull: true
  mysql:
    image: percona/percona-server:5.6
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes

pipeline:
  composer-install-lowest:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=5.6}
    volumes:
    - /cache:/cache
    commands:
      # Perform a composer install to work around an issue where an update
      # without a lock file present affects the resolving of dependencies.
      # Todo: Remove the `composer install` when the composer bug is fixed.
      # Ref. https://github.com/composer/composer/issues/7542
      # Ref. https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
      - composer install --no-ansi --no-suggest --no-progress
      - composer update --prefer-lowest --no-ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION=5.6}
    volumes:
      - /cache:/cache
    commands:
      - composer install --no-ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  site-install:
    image: fpfis/httpd-php-ci:${PHP_VERSION=5.6}
    commands:
    - ./vendor/bin/taskman drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=5.6}
    commands:
    - ./vendor/bin/grumphp run --no-ansi

matrix:
  PHP_VERSION:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  COMPOSER_BOUNDARY:
  - lowest
  - highest
